# fly.toml app configuration file generated for oimo-bot on 2023-07-25T12:01:22+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "oimo-bot"
primary_region = "nrt"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
    SWAP="true"